export function compressToBase64(o: any): string;
export function decompressFromBase64(r: any): string;
export function compressToUTF16(o: any): string;
export function decompressFromUTF16(o: any): string;
export function compressToUint8Array(o: any): Uint8Array<ArrayBuffer>;
export function decompressFromUint8Array(o: any): string;
export function compressToEncodedURIComponent(o: any): string;
export function decompressFromEncodedURIComponent(r: any): string;
export function compress(o: any): string;
export function _compress(o: any, r: any, n: any): string;
export function decompress(o: any): string;
export function _decompress(o: any, n: any, e: any): string;
